name: CTest

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      src: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y cmake build-essential libeigen3-dev libxml2-dev zlib1g-dev

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install -y cmake --version=3.28.6 `
            --no-progress `
            --installargs '"ADD_CMAKE_TO_PATH=System"' `
            --allow-downgrade

          $ver = '1.3.1'
          $zip = "$env:RUNNER_TEMP\zlib.zip"
          Invoke-WebRequest "https://zlib.net/zlib$($ver -replace '\.', '').zip" -OutFile $zip
          Expand-Archive $zip -DestinationPath $env:RUNNER_TEMP
          $src = Join-Path $env:RUNNER_TEMP "zlib-$ver"
          $bld = Join-Path $src "build"
          cmake -S "$src" -B "$bld" -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX="$bld\install" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release
          Push-Location $bld
          nmake install
          Pop-Location
          $zlibDir = Join-Path $bld "install"
          $inc = Join-Path $zlibDir "include"
          $libDir = Join-Path $zlibDir "lib"
          $static = Join-Path $libDir "zlibstatic.lib"
          $lib = Join-Path $libDir "zlib.lib"
          Copy-Item $static $lib -Force
          "CMAKE_PREFIX_PATH=$zlibDir;$env:CMAKE_PREFIX_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CMAKE_INCLUDE_PATH=$inc;$env:CMAKE_INCLUDE_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CMAKE_LIBRARY_PATH=$libDir;$env:CMAKE_LIBRARY_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "ZLIB_LIBRARY=$lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "ZLIB_INCLUDE_DIR=$inc" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          $ver = '3.4.0'
          $zip = "$env:RUNNER_TEMP\eigen.zip"
          Invoke-WebRequest "https://gitlab.com/libeigen/eigen/-/archive/$ver/eigen-$ver.zip" -OutFile $zip
          Expand-Archive $zip -DestinationPath $env:RUNNER_TEMP
          $dir = Join-Path $env:RUNNER_TEMP "eigen-$ver"
          "EIGEN3_INCLUDE_DIR=$dir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CMAKE_PREFIX_PATH=$dir;$env:CMAKE_PREFIX_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          $ver = '2.12.10'
          $zip = "$env:RUNNER_TEMP\libxml2.zip"
          Invoke-WebRequest "https://github.com/GNOME/libxml2/archive/refs/tags/v$ver.zip" -OutFile $zip
          Expand-Archive $zip -DestinationPath $env:RUNNER_TEMP
          $src = Join-Path $env:RUNNER_TEMP "libxml2-$ver"
          $installDir = Join-Path $src 'install'
          $win32 = Join-Path $src 'win32'
          Push-Location $win32
          cscript configure.js compiler=msvc prefix=$installDir iconv=no zlib=yes include=$env:ZLIB_INCLUDE_DIR lib=$env:ZLIB_LIBRARY_DIR
          (Get-Content Makefile.msvc).Replace('/OPT:NOWIN98','').Replace('zdll.lib','zlib.lib') | Set-Content Makefile.msvc
          $conf = Join-Path $src 'config.h'
          if (Test-Path $conf) {
            (Get-Content $conf) -replace '^#define snprintf.*', '// removed snprintf define' -replace '^#define vsnprintf.*', '// removed vsnprintf define' | Set-Content $conf
          }
          nmake /f Makefile.msvc
          nmake /f Makefile.msvc install
          Pop-Location
          $inc = Join-Path $installDir 'include'
          $lib = Join-Path $installDir 'lib' 'libxml2.lib'
          "CMAKE_PREFIX_PATH=$installDir;$env:CMAKE_PREFIX_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "LIBXML2_LIBRARY=$lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "LIBXML2_LIBRARIES=$lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "LIBXML2_INCLUDE_DIR=$inc" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Configure
        run: |
          cmake -S "$src" -B "$src/build" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX="$src/build/install" \
            -DBUILD_SHARED=ON \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DOB_USE_PREBUILT_BINARIES=OFF \
            -DOPENBABEL_USE_SYSTEM_INCHI=OFF \
            -DWITH_INCHI=ON
        shell: bash

      - name: Build
        run: cmake --build "$src/build" --config Release
        shell: bash

      - name: Test
        run: ctest --test-dir "$src/build" --output-on-failure -C Release
        shell: bash
